### ISSUE TITLE
"SHOW TABLES" doesn't work

### ISSUE THREAD

**Issue by inouet** [yfuruyama/spanner-cli#14]
"SHOW TABLES" will fail with the error below:

```
spanner> SHOW TABLES;
ERROR: spanner: code = "InvalidArgument", desc = "Syntax error: Unexpected \\\"-\\\" [at 1:41]\\nSELECT t.table_name AS Tables_in_xxxxx FROM information_schema.ta...\\n
```

**Comment by yfuruyama** [comment]
@inouet 
Thank you for filing a issue.
This problem occurs when the database name has `-` character.

I fixed this issue at https://github.com/yfuruyama/spanner-cli/commit/b96055d0493f287835158665c6f6e659cab1e91b , so could you `go get -u github.com/yfuruyama/spanner-cli` again?

**Comment by inouet** [comment]
@yfuruyama Thank you for your quick update.
My problem is fixed. thanks!
